[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="ticket" type="ua.nmu.airportticketoffice.entity.Ticket" --]
[#-- @ftlvariable name="tickets" type="java.util.List<ua.nmu.airportticketoffice.entity.Ticket>" --]
[#-- @ftlvariable name="schedule" type="ua.nmu.airportticketoffice.entity.Schedule" --]
[#-- @ftlvariable name="schedules" type="java.util.List<ua.nmu.airportticketoffice.entity.Schedule>" --]
[#-- @ftlvariable name="cities" type="java.util.List<ua.nmu.airportticketoffice.entity.City>" --]
[#-- @ftlvariable name="passportData" type="ua.nmu.airportticketoffice.entity.PassportData" --]
[#-- @ftlvariable name="client" type="ua.nmu.airportticketoffice.entity.Client" --]
[#-- @ftlvariable name="clients" type="java.util.List<ua.nmu.airportticketoffice.entity.Client>" --]
